cmake_minimum_required(VERSION 3.30)
project(TRABALHO_FINAL)

set(CMAKE_CXX_STANDARD 20)

add_executable(Projeto_Meta1
        main.cpp
        LeitorComandos.cpp
        Simulador.cpp
        Jardim.cpp
        Posicao.cpp
        Jardineiro.cpp
        Planta.cpp
        Ferramenta.cpp
        Visualizador.cpp
)